import type { Application } from "./types";

/**
 * The applications the demo starts with.
 * The first five belong to the demo candidate (cand-001) so the candidate
 * dashboard has something to show. The rest come from other candidates so the
 * recruiter screens have data too.
 */
export const SEED_APPLICATIONS: Application[] = [
  {
    id: "app-001",
    jobId: "job-001",
    jobTitle: "Senior Frontend Engineer",
    company: "Nimbus Labs",
    candidateId: "cand-001",
    candidateName: "Aarav Sharma",
    candidateEmail: "aarav.sharma@example.com",
    phone: "+91 98200 41122",
    location: "Bengaluru, India",
    experience: "4 years",
    currentCompany: "Bluepeak Software",
    expectedSalary: "32 LPA",
    noticePeriod: "60 days",
    coverLetter:
      "I have spent the last two years owning a design system used by three product teams, which maps almost exactly onto what you describe in this role. I would love to talk about the dashboard rebuild.",
    resumeFileName: "aarav-sharma-resume.pdf",
    portfolioUrl: "https://aaravsharma.dev",
    linkedinUrl: "https://linkedin.com/in/aarav-sharma",
    status: "Interview",
    appliedDate: "2026-08-24",
    timeline: [
      { status: "Applied", date: "2026-08-24", note: "Application submitted." },
      { status: "Under Review", date: "2026-08-26", note: "Resume reviewed by the hiring team." },
      { status: "Shortlisted", date: "2026-08-29", note: "Shortlisted for a technical conversation." },
      { status: "Interview", date: "2026-09-03", note: "Technical interview scheduled for 10 Sep, 11:00 AM." },
    ],
  },
  {
    id: "app-002",
    jobId: "job-008",
    jobTitle: "QA Automation Engineer",
    company: "Meridian Health",
    candidateId: "cand-001",
    candidateName: "Aarav Sharma",
    candidateEmail: "aarav.sharma@example.com",
    phone: "+91 98200 41122",
    location: "Bengaluru, India",
    experience: "4 years",
    currentCompany: "Bluepeak Software",
    expectedSalary: "20 LPA",
    noticePeriod: "60 days",
    coverLetter:
      "I built the Playwright suite at my current company from nothing, which is exactly the brief here.",
    resumeFileName: "aarav-sharma-resume.pdf",
    portfolioUrl: "https://aaravsharma.dev",
    linkedinUrl: "https://linkedin.com/in/aarav-sharma",
    status: "Shortlisted",
    appliedDate: "2026-08-28",
    timeline: [
      { status: "Applied", date: "2026-08-28", note: "Application submitted." },
      { status: "Under Review", date: "2026-08-31", note: "Screening in progress." },
      { status: "Shortlisted", date: "2026-09-04", note: "Moved to the shortlist. Recruiter will be in touch." },
    ],
  },
  {
    id: "app-003",
    jobId: "job-005",
    jobTitle: "DevOps Engineer",
    company: "Nimbus Labs",
    candidateId: "cand-001",
    candidateName: "Aarav Sharma",
    candidateEmail: "aarav.sharma@example.com",
    phone: "+91 98200 41122",
    location: "Bengaluru, India",
    experience: "4 years",
    currentCompany: "Bluepeak Software",
    expectedSalary: "30 LPA",
    noticePeriod: "60 days",
    coverLetter:
      "I have owned our CI pipeline and Terraform modules alongside my frontend work for the past year and would like to make that the whole job.",
    resumeFileName: "aarav-sharma-resume.pdf",
    portfolioUrl: "https://aaravsharma.dev",
    linkedinUrl: "https://linkedin.com/in/aarav-sharma",
    status: "Under Review",
    appliedDate: "2026-09-01",
    timeline: [
      { status: "Applied", date: "2026-09-01", note: "Application submitted." },
      { status: "Under Review", date: "2026-09-03", note: "Application is with the hiring manager." },
    ],
  },
  {
    id: "app-004",
    jobId: "job-003",
    jobTitle: "Product Designer",
    company: "Kite & Co.",
    candidateId: "cand-001",
    candidateName: "Aarav Sharma",
    candidateEmail: "aarav.sharma@example.com",
    phone: "+91 98200 41122",
    location: "Bengaluru, India",
    experience: "4 years",
    currentCompany: "Bluepeak Software",
    expectedSalary: "24 LPA",
    noticePeriod: "60 days",
    coverLetter:
      "I know this is a designer role and I am an engineer, but I have run our design system and I would like to make the case for a hybrid profile.",
    resumeFileName: "aarav-sharma-resume.pdf",
    portfolioUrl: "https://aaravsharma.dev",
    linkedinUrl: "https://linkedin.com/in/aarav-sharma",
    status: "Rejected",
    appliedDate: "2026-08-18",
    timeline: [
      { status: "Applied", date: "2026-08-18", note: "Application submitted." },
      { status: "Under Review", date: "2026-08-20", note: "Portfolio reviewed." },
      { status: "Rejected", date: "2026-08-23", note: "Looking for a dedicated product design background." },
    ],
  },
  {
    id: "app-005",
    jobId: "job-004",
    jobTitle: "Data Analyst",
    company: "Harbour Retail Group",
    candidateId: "cand-001",
    candidateName: "Aarav Sharma",
    candidateEmail: "aarav.sharma@example.com",
    phone: "+91 98200 41122",
    location: "Bengaluru, India",
    experience: "4 years",
    currentCompany: "Bluepeak Software",
    expectedSalary: "15 LPA",
    noticePeriod: "60 days",
    coverLetter:
      "I do a lot of analytics work alongside my frontend role and would like to move into it properly.",
    resumeFileName: "aarav-sharma-resume.pdf",
    portfolioUrl: "https://aaravsharma.dev",
    linkedinUrl: "https://linkedin.com/in/aarav-sharma",
    status: "Applied",
    appliedDate: "2026-09-05",
    timeline: [{ status: "Applied", date: "2026-09-05", note: "Application submitted." }],
  },
  {
    id: "app-006",
    jobId: "job-002",
    jobTitle: "Backend Engineer (Python)",
    company: "Finwise Technologies",
    candidateId: "cand-002",
    candidateName: "Priya Nair",
    candidateEmail: "priya.nair@example.com",
    phone: "+91 99401 77310",
    location: "Chennai, India",
    experience: "7 years",
    currentCompany: "Corevault Systems",
    expectedSalary: "24 LPA",
    noticePeriod: "90 days",
    coverLetter:
      "Seven years of Python backend work, the last three on a payments platform. Happy to relocate to Pune.",
    resumeFileName: "priya-nair-cv.pdf",
    portfolioUrl: "",
    linkedinUrl: "https://linkedin.com/in/priya-nair",
    status: "Interview",
    appliedDate: "2026-08-31",
    timeline: [
      { status: "Applied", date: "2026-08-31", note: "Application submitted." },
      { status: "Under Review", date: "2026-09-01", note: "Strong profile, moving forward." },
      { status: "Shortlisted", date: "2026-09-02", note: "Shortlisted for the system design round." },
      { status: "Interview", date: "2026-09-05", note: "System design interview on 11 Sep." },
    ],
  },
  {
    id: "app-007",
    jobId: "job-005",
    jobTitle: "DevOps Engineer",
    company: "Nimbus Labs",
    candidateId: "cand-003",
    candidateName: "Vikram Joshi",
    candidateEmail: "vikram.joshi@example.com",
    phone: "+91 90042 66127",
    location: "Bengaluru, India",
    experience: "6 years",
    currentCompany: "Skyforge Cloud",
    expectedSalary: "42 LPA",
    noticePeriod: "30 days",
    coverLetter:
      "I migrated 200+ manually provisioned resources into Terraform at Skyforge. Your description reads like my last two years.",
    resumeFileName: "vikram-joshi-resume.pdf",
    portfolioUrl: "https://github.com/vikramj",
    linkedinUrl: "https://linkedin.com/in/vikram-joshi",
    status: "Hired",
    appliedDate: "2026-08-08",
    timeline: [
      { status: "Applied", date: "2026-08-08", note: "Application submitted." },
      { status: "Shortlisted", date: "2026-08-13", note: "Shortlisted - strong Terraform background." },
      { status: "Interview", date: "2026-08-19", note: "Panel interview completed." },
      { status: "Hired", date: "2026-08-26", note: "Offer accepted. Joining 1 Oct 2026." },
    ],
  },
  {
    id: "app-008",
    jobId: "job-006",
    jobTitle: "Frontend Developer Intern",
    company: "Kite & Co.",
    candidateId: "cand-004",
    candidateName: "Ananya Iyer",
    candidateEmail: "ananya.iyer@example.com",
    phone: "+91 89760 31245",
    location: "Hyderabad, India",
    experience: "Fresher",
    currentCompany: "-",
    expectedSalary: "4 LPA",
    noticePeriod: "Immediate",
    coverLetter:
      "Final year CS student. I have built three React projects, including a college event portal now used by 900 students.",
    resumeFileName: "ananya-iyer-resume.pdf",
    portfolioUrl: "https://ananyaiyer.vercel.app",
    linkedinUrl: "https://linkedin.com/in/ananya-iyer",
    status: "Applied",
    appliedDate: "2026-09-06",
    timeline: [{ status: "Applied", date: "2026-09-06", note: "Application submitted." }],
  },
  {
    id: "app-009",
    jobId: "job-003",
    jobTitle: "Product Designer",
    company: "Kite & Co.",
    candidateId: "cand-005",
    candidateName: "Rohan Deshpande",
    candidateEmail: "rohan.deshpande@example.com",
    phone: "+91 98902 55418",
    location: "Pune, India",
    experience: "5 years",
    currentCompany: "Studio Kernel",
    expectedSalary: "26 LPA",
    noticePeriod: "45 days",
    coverLetter:
      "Five years designing B2B tools, including two years on a clinic management product. I have attached three case studies.",
    resumeFileName: "rohan-deshpande-portfolio.pdf",
    portfolioUrl: "https://rohand.design",
    linkedinUrl: "https://linkedin.com/in/rohan-deshpande",
    status: "Under Review",
    appliedDate: "2026-09-05",
    timeline: [
      { status: "Applied", date: "2026-09-05", note: "Application submitted." },
      { status: "Under Review", date: "2026-09-06", note: "Portfolio being reviewed." },
    ],
  },
];
