import type { ExperienceLevel, Job, JobType, WorkMode } from "./types";

/** Option lists reused by the filter panel and the create/edit job forms. */
export const JOB_TYPES: JobType[] = ["Full-time", "Part-time", "Contract", "Internship"];
export const WORK_MODES: WorkMode[] = ["On-site", "Hybrid", "Remote"];
export const EXPERIENCE_LEVELS: ExperienceLevel[] = ["Entry", "Mid", "Senior", "Lead"];
export const DEPARTMENTS = [
  "Engineering",
  "Design",
  "Product",
  "Data",
  "Marketing",
  "Sales",
  "Finance",
  "Human Resources",
];

/**
 * The seed job list - the "database" the demo starts with.
 * Recruiters can add, edit and delete jobs. Those changes are kept in
 * localStorage (see lib/hooks.ts) and start from this array.
 */
export const SEED_JOBS: Job[] = [
  {
    id: "job-001",
    title: "Senior Frontend Engineer",
    company: "Nimbus Labs",
    companyInitials: "NL",
    location: "Bengaluru, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "4 - 7 years",
    experienceLevel: "Senior",
    salaryMin: 24,
    salaryMax: 38,
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    description:
      "We are looking for a Senior Frontend Engineer to lead the rebuild of our customer dashboard. You will own the shared component library and mentor two mid-level engineers on the team.",
    requirements: [
      "4+ years building production React applications",
      "Strong TypeScript skills and a good eye for API design",
      "Hands-on experience with Next.js",
      "Understanding of web accessibility",
    ],
    benefits: ["Health insurance", "Annual learning budget", "Hybrid - 2 days in office"],
    department: "Engineering",
    openings: 2,
    postedDate: "2026-09-02",
    status: "Open",
  },
  {
    id: "job-002",
    title: "Backend Engineer (Python)",
    company: "Finwise Technologies",
    companyInitials: "FT",
    location: "Pune, India",
    jobType: "Full-time",
    workMode: "On-site",
    experience: "2 - 4 years",
    experienceLevel: "Mid",
    salaryMin: 14,
    salaryMax: 22,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker"],
    description:
      "Join the payments team building the services that move money for our lending partners. You will design APIs that need to be correct first and fast second, with real ownership of what you ship.",
    requirements: [
      "2+ years of backend development in Python",
      "Experience with FastAPI, Django or Flask",
      "Solid PostgreSQL knowledge",
      "Familiarity with Docker",
    ],
    benefits: ["Performance bonus", "Free lunch", "Relocation support"],
    department: "Engineering",
    openings: 3,
    postedDate: "2026-08-30",
    status: "Open",
  },
  {
    id: "job-003",
    title: "Product Designer",
    company: "Kite & Co.",
    companyInitials: "KC",
    location: "Remote, India",
    jobType: "Full-time",
    workMode: "Remote",
    experience: "3 - 6 years",
    experienceLevel: "Mid",
    salaryMin: 18,
    salaryMax: 28,
    skills: ["Figma", "User Research", "Design Systems", "Prototyping"],
    description:
      "We are a fully remote team of eleven building scheduling software for clinics. As our second designer you will run discovery, ship end-to-end flows and help grow our young design system.",
    requirements: [
      "3+ years designing web products",
      "A portfolio that shows your thinking, not just final screens",
      "Confident in Figma, including components and auto layout",
      "Experience running your own user research",
    ],
    benefits: ["Fully remote", "Home office budget", "Annual team offsite"],
    department: "Design",
    openings: 1,
    postedDate: "2026-09-04",
    status: "Open",
  },
  {
    id: "job-004",
    title: "Data Analyst",
    company: "Harbour Retail Group",
    companyInitials: "HR",
    location: "Mumbai, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "1 - 3 years",
    experienceLevel: "Entry",
    salaryMin: 8,
    salaryMax: 14,
    skills: ["SQL", "Python", "Power BI", "Excel"],
    description:
      "Sit with the merchandising team and answer the questions that decide what our stores stock next season. Plenty of mentoring - a great first or second analytics role.",
    requirements: [
      "1+ year in an analytics role, or a strong internship",
      "Confident with SQL joins and aggregation",
      "Working knowledge of Python or R",
      "Clear written and spoken communication",
    ],
    benefits: ["Employee discount", "Health cover", "Structured mentoring"],
    department: "Data",
    openings: 2,
    postedDate: "2026-08-27",
    status: "Open",
  },
  {
    id: "job-005",
    title: "DevOps Engineer",
    company: "Nimbus Labs",
    companyInitials: "NL",
    location: "Bengaluru, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "5 - 8 years",
    experienceLevel: "Senior",
    salaryMin: 28,
    salaryMax: 45,
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD"],
    description:
      "Own the platform that forty engineers deploy to every day. We have outgrown our hand-rolled scripts and need someone to bring real infrastructure-as-code discipline to our AWS setup.",
    requirements: [
      "5+ years in DevOps, SRE or platform engineering",
      "Production experience running Kubernetes",
      "Strong Terraform and AWS knowledge",
      "Scripting in Python, Go or Bash",
    ],
    benefits: ["Stock options", "Health insurance", "Conference budget"],
    department: "Engineering",
    openings: 1,
    postedDate: "2026-08-21",
    status: "Open",
  },
  {
    id: "job-006",
    title: "Frontend Developer Intern",
    company: "Kite & Co.",
    companyInitials: "KC",
    location: "Remote, India",
    jobType: "Internship",
    workMode: "Remote",
    experience: "0 - 1 years",
    experienceLevel: "Entry",
    salaryMin: 3,
    salaryMax: 5,
    skills: ["HTML", "CSS", "JavaScript", "React"],
    description:
      "A six month paid internship for someone early in their journey. You will pair with senior engineers, ship small features to real users, and leave with a portfolio you are proud of.",
    requirements: [
      "Comfortable with HTML, CSS and JavaScript fundamentals",
      "Some exposure to React from coursework or personal projects",
      "Able to use Git and open a pull request",
      "Curious, and happy to ask questions",
    ],
    benefits: ["Paid internship", "Dedicated mentor", "Possible full-time offer"],
    department: "Engineering",
    openings: 4,
    postedDate: "2026-09-05",
    status: "Open",
  },
  {
    id: "job-007",
    title: "HR Business Partner",
    company: "Harbour Retail Group",
    companyInitials: "HR",
    location: "Gurugram, India",
    jobType: "Full-time",
    workMode: "On-site",
    experience: "5 - 9 years",
    experienceLevel: "Senior",
    salaryMin: 20,
    salaryMax: 30,
    skills: ["Employee Relations", "Performance Management", "Coaching"],
    description:
      "Partner with two business units totalling 600 people. You will coach managers, run the performance cycle, and be the person people trust when something difficult comes up.",
    requirements: [
      "5+ years in an HR generalist or HRBP role",
      "Strong grounding in Indian labour law",
      "Experience handling employee relations cases end to end",
      "Comfortable presenting to senior leadership",
    ],
    benefits: ["Family health cover", "Annual bonus", "Employee discount"],
    department: "Human Resources",
    openings: 1,
    postedDate: "2026-08-19",
    status: "Open",
  },
  {
    id: "job-008",
    title: "QA Automation Engineer",
    company: "Meridian Health",
    companyInitials: "MH",
    location: "Chennai, India",
    jobType: "Contract",
    workMode: "Remote",
    experience: "3 - 6 years",
    experienceLevel: "Mid",
    salaryMin: 12,
    salaryMax: 20,
    skills: ["Playwright", "TypeScript", "API Testing", "CI/CD"],
    description:
      "A twelve month contract to build our end-to-end test suite from scratch. Regression testing is manual today and takes three days - your job is to make that a twenty minute pipeline run.",
    requirements: [
      "3+ years in test automation",
      "Strong with Playwright, Cypress or similar",
      "Able to write maintainable TypeScript",
      "Experience introducing automation where none existed",
    ],
    benefits: ["Fully remote", "12 month contract", "Equipment provided"],
    department: "Engineering",
    openings: 1,
    postedDate: "2026-08-14",
    status: "Open",
  },
  {
    id: "job-009",
    title: "Product Manager",
    company: "Meridian Health",
    companyInitials: "MH",
    location: "Pune, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "5 - 8 years",
    experienceLevel: "Senior",
    salaryMin: 30,
    salaryMax: 46,
    skills: ["Product Strategy", "User Research", "Roadmapping", "SQL"],
    description:
      "Own the patient portal roadmap end to end. You will sit between clinicians, engineers and compliance, and decide what we build next for 90,000 monthly users.",
    requirements: [
      "5+ years in product management for a software product",
      "Comfortable writing your own SQL to answer a question",
      "Experience shipping in a regulated industry",
      "Strong written communication",
    ],
    benefits: ["Health insurance", "Hybrid working", "Annual bonus"],
    department: "Product",
    openings: 1,
    postedDate: "2026-09-06",
    status: "Open",
  },
  {
    id: "job-010",
    title: "Machine Learning Engineer",
    company: "Finwise Technologies",
    companyInitials: "FT",
    location: "Bengaluru, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "4 - 7 years",
    experienceLevel: "Senior",
    salaryMin: 30,
    salaryMax: 48,
    skills: ["Python", "PyTorch", "MLOps", "SQL"],
    description:
      "Take our credit risk models from notebooks into production. You will own the full lifecycle - training, deployment, monitoring and retraining.",
    requirements: [
      "4+ years applying machine learning to real products",
      "Strong Python and PyTorch or TensorFlow",
      "Experience deploying and monitoring models in production",
      "Comfortable explaining a model to a non-technical audience",
    ],
    benefits: ["Performance bonus", "Relocation support", "Conference budget"],
    department: "Data",
    openings: 1,
    postedDate: "2026-09-03",
    status: "Open",
  },
  {
    id: "job-011",
    title: "Mobile Developer (React Native)",
    company: "Nimbus Labs",
    companyInitials: "NL",
    location: "Hyderabad, India",
    jobType: "Full-time",
    workMode: "Remote",
    experience: "3 - 5 years",
    experienceLevel: "Mid",
    salaryMin: 18,
    salaryMax: 30,
    skills: ["React Native", "TypeScript", "iOS", "Android"],
    description:
      "Build the mobile companion app to our web dashboard. Greenfield project, one other engineer, and a designer who already has the flows drawn up.",
    requirements: [
      "3+ years shipping React Native apps to both stores",
      "Solid TypeScript",
      "Experience with offline-first data and push notifications",
      "You have dealt with app store review at least once",
    ],
    benefits: ["Fully remote", "Stock options", "Device budget"],
    department: "Engineering",
    openings: 2,
    postedDate: "2026-09-01",
    status: "Open",
  },
  {
    id: "job-012",
    title: "UX Researcher",
    company: "Meridian Health",
    companyInitials: "MH",
    location: "Remote, India",
    jobType: "Contract",
    workMode: "Remote",
    experience: "3 - 6 years",
    experienceLevel: "Mid",
    salaryMin: 14,
    salaryMax: 24,
    skills: ["User Interviews", "Usability Testing", "Survey Design", "Synthesis"],
    description:
      "A nine month contract to build a research practice from scratch. Right now decisions are made on opinion - your job is to replace that with evidence.",
    requirements: [
      "3+ years running qualitative and quantitative research",
      "Able to recruit your own participants",
      "Experience presenting findings that changed a roadmap",
      "Healthcare exposure is a bonus, not a requirement",
    ],
    benefits: ["Fully remote", "9 month contract", "Flexible hours"],
    department: "Design",
    openings: 1,
    postedDate: "2026-08-29",
    status: "Open",
  },
  {
    id: "job-013",
    title: "Digital Marketing Manager",
    company: "Harbour Retail Group",
    companyInitials: "HR",
    location: "Gurugram, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "5 - 8 years",
    experienceLevel: "Senior",
    salaryMin: 20,
    salaryMax: 32,
    skills: ["SEO", "Google Ads", "Analytics", "Content Strategy"],
    description:
      "Own paid and organic acquisition across 180 stores and the online shop. Real budget, real targets, and the freedom to decide where the money goes.",
    requirements: [
      "5+ years running digital campaigns with your own budget",
      "Hands-on with Google Ads and at least one social ad platform",
      "Comfortable reading analytics reports and drawing conclusions",
      "Experience managing one or two junior marketers",
    ],
    benefits: ["Performance bonus", "Employee discount", "Learning budget"],
    department: "Marketing",
    openings: 1,
    postedDate: "2026-08-26",
    status: "Open",
  },
  {
    id: "job-014",
    title: "Financial Analyst",
    company: "Finwise Technologies",
    companyInitials: "FT",
    location: "Mumbai, India",
    jobType: "Full-time",
    workMode: "On-site",
    experience: "2 - 5 years",
    experienceLevel: "Mid",
    salaryMin: 10,
    salaryMax: 18,
    skills: ["Financial Modelling", "Excel", "Forecasting", "SQL"],
    description:
      "Support the finance director with budgeting, forecasting and unit economics for our lending products. Plenty of exposure to the leadership team.",
    requirements: [
      "2+ years in an FP&A or financial analysis role",
      "Advanced Excel including pivot tables and lookups",
      "Part-qualified or qualified accountant (CA / CMA / ACCA)",
      "Able to explain a variance without jargon",
    ],
    benefits: ["Study support", "Annual bonus", "Free lunch"],
    department: "Finance",
    openings: 1,
    postedDate: "2026-08-22",
    status: "Open",
  },
  {
    id: "job-015",
    title: "Customer Success Executive",
    company: "Kite & Co.",
    companyInitials: "KC",
    location: "Remote, India",
    jobType: "Part-time",
    workMode: "Remote",
    experience: "1 - 3 years",
    experienceLevel: "Entry",
    salaryMin: 5,
    salaryMax: 9,
    skills: ["Communication", "Onboarding", "CRM", "Documentation"],
    description:
      "A part-time role (25 hours a week) helping new clinics get set up and stay happy. Ideal if you want meaningful work without a full week.",
    requirements: [
      "1+ year in customer success, support or account management",
      "Excellent written English",
      "Comfortable running video calls with non-technical users",
      "Organised - you will juggle many accounts at once",
    ],
    benefits: ["25 hours per week", "Fully remote", "Flexible schedule"],
    department: "Sales",
    openings: 2,
    postedDate: "2026-08-20",
    status: "Open",
  },
  {
    id: "job-016",
    title: "Technical Recruiter",
    company: "Nimbus Labs",
    companyInitials: "NL",
    location: "Bengaluru, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "3 - 6 years",
    experienceLevel: "Mid",
    salaryMin: 14,
    salaryMax: 24,
    skills: ["Sourcing", "Interviewing", "Stakeholder Management", "ATS"],
    description:
      "Hire the engineers who build our platform. You will own the whole funnel, from first outreach to offer, working directly with the engineering managers.",
    requirements: [
      "3+ years recruiting software engineers",
      "Confident sourcing passive candidates, not just screening inbound",
      "Able to hold your own in a conversation about tech stacks",
      "Experience running an ATS end to end",
    ],
    benefits: ["Stock options", "Health insurance", "Hybrid working"],
    department: "Human Resources",
    openings: 1,
    postedDate: "2026-08-17",
    status: "Open",
  },
  {
    id: "job-017",
    title: "Senior Product Designer",
    company: "Nimbus Labs",
    companyInitials: "NL",
    location: "Bengaluru, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "6 - 9 years",
    experienceLevel: "Senior",
    salaryMin: 32,
    salaryMax: 48,
    skills: ["Figma", "Design Systems", "Interaction Design", "Prototyping"],
    description:
      "Lead design for our core platform and act as the design voice in quarterly planning. You will have one designer reporting to you and a mature design system to build on.",
    requirements: [
      "6+ years designing complex B2B software",
      "Experience owning a design system in production",
      "Comfortable presenting work to executives",
      "A portfolio that shows process, not just polish",
    ],
    benefits: ["Stock options", "Health insurance", "Conference budget"],
    department: "Design",
    openings: 1,
    postedDate: "2026-09-06",
    status: "Open",
  },
  {
    id: "job-018",
    title: "Data Engineer",
    company: "Finwise Technologies",
    companyInitials: "FT",
    location: "Pune, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "3 - 6 years",
    experienceLevel: "Mid",
    salaryMin: 20,
    salaryMax: 32,
    skills: ["Python", "Airflow", "dbt", "Snowflake", "SQL"],
    description:
      "Build the pipelines that feed our risk models and finance reporting. Today most of it is cron jobs and hope - your job is to replace that with something we can trust.",
    requirements: [
      "3+ years building production data pipelines",
      "Strong SQL and Python",
      "Hands-on with Airflow, dbt or similar",
      "Care about data quality and lineage",
    ],
    benefits: ["Performance bonus", "Free lunch", "Learning budget"],
    department: "Data",
    openings: 2,
    postedDate: "2026-09-05",
    status: "Open",
  },
  {
    id: "job-019",
    title: "Content Writer",
    company: "Kite & Co.",
    companyInitials: "KC",
    location: "Remote, India",
    jobType: "Part-time",
    workMode: "Remote",
    experience: "1 - 3 years",
    experienceLevel: "Entry",
    salaryMin: 4,
    salaryMax: 8,
    skills: ["Copywriting", "SEO", "Editing", "Research"],
    description:
      "A part-time role writing help articles, release notes and the occasional blog post for our clinic scheduling product. Twenty hours a week, entirely remote.",
    requirements: [
      "1+ year writing for a software product or agency",
      "Excellent written English",
      "Able to interview a subject expert and turn it into clear prose",
      "Basic understanding of SEO",
    ],
    benefits: ["20 hours per week", "Fully remote", "Flexible schedule"],
    department: "Marketing",
    openings: 1,
    postedDate: "2026-09-04",
    status: "Open",
  },
  {
    id: "job-020",
    title: "Android Developer",
    company: "Meridian Health",
    companyInitials: "MH",
    location: "Chennai, India",
    jobType: "Full-time",
    workMode: "On-site",
    experience: "2 - 5 years",
    experienceLevel: "Mid",
    salaryMin: 14,
    salaryMax: 24,
    skills: ["Kotlin", "Jetpack Compose", "REST APIs", "Testing"],
    description:
      "Own the Android side of our patient app, used in 40 clinics across Tamil Nadu. You will work closely with one iOS developer and a shared backend team.",
    requirements: [
      "2+ years shipping native Android apps",
      "Strong Kotlin, ideally with Jetpack Compose",
      "Experience with offline data and background sync",
      "Comfortable writing instrumentation tests",
    ],
    benefits: ["Health insurance", "Annual bonus", "Device budget"],
    department: "Engineering",
    openings: 1,
    postedDate: "2026-09-02",
    status: "Open",
  },
  {
    id: "job-021",
    title: "Site Reliability Engineer",
    company: "Nimbus Labs",
    companyInitials: "NL",
    location: "Bengaluru, India",
    jobType: "Full-time",
    workMode: "Remote",
    experience: "7 - 10 years",
    experienceLevel: "Lead",
    salaryMin: 42,
    salaryMax: 60,
    skills: ["Kubernetes", "Go", "Observability", "Incident Response"],
    description:
      "Set the reliability standard for the whole engineering org. You will define SLOs, run blameless post-mortems and make on-call something people are not afraid of.",
    requirements: [
      "7+ years in SRE or platform engineering",
      "Deep Kubernetes and Linux knowledge",
      "Experience defining SLOs and error budgets",
      "You have led incident response for a real outage",
    ],
    benefits: ["Fully remote", "Stock options", "On-call allowance"],
    department: "Engineering",
    openings: 1,
    postedDate: "2026-08-31",
    status: "Open",
  },
  {
    id: "job-022",
    title: "Business Analyst",
    company: "Harbour Retail Group",
    companyInitials: "HR",
    location: "Mumbai, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "3 - 6 years",
    experienceLevel: "Mid",
    salaryMin: 14,
    salaryMax: 22,
    skills: ["Requirements Gathering", "SQL", "Process Mapping", "Stakeholder Management"],
    description:
      "Sit between the merchandising team and IT, turning vague business asks into specifications engineers can actually build from.",
    requirements: [
      "3+ years as a business or systems analyst",
      "Confident writing your own SQL",
      "Experience documenting processes end to end",
      "Retail or supply chain exposure is a plus",
    ],
    benefits: ["Employee discount", "Health cover", "Flexible hours"],
    department: "Product",
    openings: 1,
    postedDate: "2026-08-30",
    status: "Open",
  },
  {
    id: "job-023",
    title: "Accounts Executive",
    company: "Harbour Retail Group",
    companyInitials: "HR",
    location: "Kolkata, India",
    jobType: "Full-time",
    workMode: "On-site",
    experience: "0 - 2 years",
    experienceLevel: "Entry",
    salaryMin: 4,
    salaryMax: 7,
    skills: ["Tally", "Excel", "Reconciliation", "GST"],
    description:
      "Handle day-to-day bookkeeping for the east region: vendor invoices, reconciliations and GST filings. A solid first finance role with a supportive team.",
    requirements: [
      "0-2 years in an accounts role, or a fresh B.Com",
      "Working knowledge of Tally and Excel",
      "Familiar with GST basics",
      "Careful with detail",
    ],
    benefits: ["Health cover", "Employee discount", "Study support"],
    department: "Finance",
    openings: 2,
    postedDate: "2026-08-28",
    status: "Open",
  },
  {
    id: "job-024",
    title: "Inside Sales Representative",
    company: "Finwise Technologies",
    companyInitials: "FT",
    location: "Gurugram, India",
    jobType: "Full-time",
    workMode: "On-site",
    experience: "1 - 3 years",
    experienceLevel: "Entry",
    salaryMin: 6,
    salaryMax: 12,
    skills: ["Lead Qualification", "CRM", "Cold Calling", "Negotiation"],
    description:
      "Qualify inbound leads from lending partners and book demos for the field team. Uncapped incentive on top of base.",
    requirements: [
      "1+ year in inside sales or lead generation",
      "Comfortable on the phone all day",
      "Experience with a CRM such as Salesforce or HubSpot",
      "Fluent in English and Hindi",
    ],
    benefits: ["Uncapped incentive", "Free lunch", "Health cover"],
    department: "Sales",
    openings: 3,
    postedDate: "2026-08-27",
    status: "Open",
  },
  {
    id: "job-025",
    title: "Engineering Manager",
    company: "Nimbus Labs",
    companyInitials: "NL",
    location: "Bengaluru, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "8 - 12 years",
    experienceLevel: "Lead",
    salaryMin: 45,
    salaryMax: 65,
    skills: ["People Management", "System Design", "Hiring", "Agile"],
    description:
      "Lead two squads - eleven engineers - building our core platform. We want a manager who still reads code but whose main output is a healthy, effective team.",
    requirements: [
      "3+ years managing engineers on top of a strong IC background",
      "Track record shipping complex platform work",
      "Experience hiring and growing engineers",
      "Clear communicator with senior stakeholders",
    ],
    benefits: ["Stock options", "Leadership coaching", "Conference budget"],
    department: "Engineering",
    openings: 1,
    postedDate: "2026-08-25",
    status: "Open",
  },
  {
    id: "job-026",
    title: "Data Science Intern",
    company: "Harbour Retail Group",
    companyInitials: "HR",
    location: "Mumbai, India",
    jobType: "Internship",
    workMode: "Hybrid",
    experience: "0 - 1 years",
    experienceLevel: "Entry",
    salaryMin: 3,
    salaryMax: 5,
    skills: ["Python", "pandas", "Statistics", "SQL"],
    description:
      "A six month internship on the merchandising analytics team. You will work on demand forecasting with a mentor and present your findings at the end.",
    requirements: [
      "Studying statistics, maths, CS or similar",
      "Comfortable with Python and pandas",
      "Some exposure to SQL",
      "Curious and happy to ask questions",
    ],
    benefits: ["Paid internship", "Dedicated mentor", "Possible full-time offer"],
    department: "Data",
    openings: 2,
    postedDate: "2026-08-24",
    status: "Open",
  },
  {
    id: "job-027",
    title: "Security Engineer",
    company: "Finwise Technologies",
    companyInitials: "FT",
    location: "Bengaluru, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "4 - 8 years",
    experienceLevel: "Senior",
    salaryMin: 30,
    salaryMax: 46,
    skills: ["AppSec", "Threat Modelling", "Penetration Testing", "Cloud Security"],
    description:
      "We move money, so security is not a side project. You will run our application security programme, from threat modelling through to fixing what you find.",
    requirements: [
      "4+ years in application or cloud security",
      "Able to read code and spot the problem",
      "Experience with threat modelling and secure design reviews",
      "Relevant certification is welcome but not required",
    ],
    benefits: ["Performance bonus", "Certification reimbursement", "Health cover"],
    department: "Engineering",
    openings: 1,
    postedDate: "2026-08-23",
    status: "Open",
  },
  {
    id: "job-028",
    title: "Learning & Development Lead",
    company: "Harbour Retail Group",
    companyInitials: "HR",
    location: "Gurugram, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "7 - 11 years",
    experienceLevel: "Lead",
    salaryMin: 26,
    salaryMax: 38,
    skills: ["Programme Design", "Facilitation", "Coaching", "Vendor Management"],
    description:
      "Build the training function for 4,000 store and head-office employees. Currently training is ad hoc - you will give it structure, a budget and measurable outcomes.",
    requirements: [
      "7+ years in learning and development",
      "Experience designing programmes, not just booking vendors",
      "Confident facilitating a room of forty people",
      "Able to show the impact of a programme with data",
    ],
    benefits: ["Family health cover", "Annual bonus", "Employee discount"],
    department: "Human Resources",
    openings: 1,
    postedDate: "2026-08-21",
    status: "Open",
  },
  {
    id: "job-029",
    title: "Salesforce Administrator",
    company: "Meridian Health",
    companyInitials: "MH",
    location: "Remote, India",
    jobType: "Contract",
    workMode: "Remote",
    experience: "3 - 6 years",
    experienceLevel: "Mid",
    salaryMin: 12,
    salaryMax: 20,
    skills: ["Salesforce", "Flows", "Reports", "Data Migration"],
    description:
      "A nine month contract to tidy up a Salesforce org that has grown organically for four years. Deduplicate, rebuild the reporting, and document what you did.",
    requirements: [
      "3+ years administering Salesforce",
      "Strong with Flows and validation rules",
      "Experience with a real data migration",
      "Salesforce Administrator certification",
    ],
    benefits: ["Fully remote", "9 month contract", "Equipment provided"],
    department: "Sales",
    openings: 1,
    postedDate: "2026-08-18",
    status: "Open",
  },
  {
    id: "job-030",
    title: "Brand Designer",
    company: "Kite & Co.",
    companyInitials: "KC",
    location: "Remote, India",
    jobType: "Full-time",
    workMode: "Remote",
    experience: "3 - 6 years",
    experienceLevel: "Mid",
    salaryMin: 16,
    salaryMax: 26,
    skills: ["Brand Identity", "Illustration", "Motion", "Typography"],
    description:
      "Own how Kite & Co. looks and sounds everywhere that is not the product - website, decks, social, conference stands. Our brand is five years old and due a refresh.",
    requirements: [
      "3+ years in brand or marketing design",
      "A portfolio with at least one identity system you led",
      "Comfortable with motion basics",
      "Able to art-direct a freelancer",
    ],
    benefits: ["Fully remote", "Home office budget", "Annual team offsite"],
    department: "Design",
    openings: 1,
    postedDate: "2026-08-16",
    status: "Open",
  },
];

/** Every distinct company in the seed data. */
export const COMPANIES = Array.from(new Set(SEED_JOBS.map((job) => job.company))).sort();
