import type { ExperienceLevel, Job, JobType, WorkMode } from "./types";

/** Option lists reused by the filter panel and the create/edit job forms. */
export const JOB_TYPES: JobType[] = ["Full-time", "Part-time", "Contract", "Internship"];
export const WORK_MODES: WorkMode[] = ["On-site", "Hybrid", "Remote"];
export const EXPERIENCE_LEVELS: ExperienceLevel[] = ["Entry", "Mid", "Senior", "Lead"];
export const DEPARTMENTS = ["Engineering", "Design", "Data", "Human Resources"];

/**
 * The seed job list - the "database" the demo starts with.
 * Recruiters can add, edit and delete jobs. Those changes are kept in
 * localStorage (see lib/hooks.ts) and start from this array.
 */
export const SEED_JOBS: Job[] = [
  {
    id: "job-001",
    title: "Senior Frontend Engineer",
    company: "Nimbus Labs",
    companyInitials: "NL",
    location: "Bengaluru, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "4 - 7 years",
    experienceLevel: "Senior",
    salaryMin: 24,
    salaryMax: 38,
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    description:
      "We are looking for a Senior Frontend Engineer to lead the rebuild of our customer dashboard. You will own the shared component library and mentor two mid-level engineers on the team.",
    requirements: [
      "4+ years building production React applications",
      "Strong TypeScript skills and a good eye for API design",
      "Hands-on experience with Next.js",
      "Understanding of web accessibility",
    ],
    benefits: ["Health insurance", "Annual learning budget", "Hybrid - 2 days in office"],
    department: "Engineering",
    openings: 2,
    postedDate: "2026-09-02",
    status: "Open",
  },
  {
    id: "job-002",
    title: "Backend Engineer (Python)",
    company: "Finwise Technologies",
    companyInitials: "FT",
    location: "Pune, India",
    jobType: "Full-time",
    workMode: "On-site",
    experience: "2 - 4 years",
    experienceLevel: "Mid",
    salaryMin: 14,
    salaryMax: 22,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker"],
    description:
      "Join the payments team building the services that move money for our lending partners. You will design APIs that need to be correct first and fast second, with real ownership of what you ship.",
    requirements: [
      "2+ years of backend development in Python",
      "Experience with FastAPI, Django or Flask",
      "Solid PostgreSQL knowledge",
      "Familiarity with Docker",
    ],
    benefits: ["Performance bonus", "Free lunch", "Relocation support"],
    department: "Engineering",
    openings: 3,
    postedDate: "2026-08-30",
    status: "Open",
  },
  {
    id: "job-003",
    title: "Product Designer",
    company: "Kite & Co.",
    companyInitials: "KC",
    location: "Remote, India",
    jobType: "Full-time",
    workMode: "Remote",
    experience: "3 - 6 years",
    experienceLevel: "Mid",
    salaryMin: 18,
    salaryMax: 28,
    skills: ["Figma", "User Research", "Design Systems", "Prototyping"],
    description:
      "We are a fully remote team of eleven building scheduling software for clinics. As our second designer you will run discovery, ship end-to-end flows and help grow our young design system.",
    requirements: [
      "3+ years designing web products",
      "A portfolio that shows your thinking, not just final screens",
      "Confident in Figma, including components and auto layout",
      "Experience running your own user research",
    ],
    benefits: ["Fully remote", "Home office budget", "Annual team offsite"],
    department: "Design",
    openings: 1,
    postedDate: "2026-09-04",
    status: "Open",
  },
  {
    id: "job-004",
    title: "Data Analyst",
    company: "Harbour Retail Group",
    companyInitials: "HR",
    location: "Mumbai, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "1 - 3 years",
    experienceLevel: "Entry",
    salaryMin: 8,
    salaryMax: 14,
    skills: ["SQL", "Python", "Power BI", "Excel"],
    description:
      "Sit with the merchandising team and answer the questions that decide what our stores stock next season. Plenty of mentoring - a great first or second analytics role.",
    requirements: [
      "1+ year in an analytics role, or a strong internship",
      "Confident with SQL joins and aggregation",
      "Working knowledge of Python or R",
      "Clear written and spoken communication",
    ],
    benefits: ["Employee discount", "Health cover", "Structured mentoring"],
    department: "Data",
    openings: 2,
    postedDate: "2026-08-27",
    status: "Open",
  },
  {
    id: "job-005",
    title: "DevOps Engineer",
    company: "Nimbus Labs",
    companyInitials: "NL",
    location: "Bengaluru, India",
    jobType: "Full-time",
    workMode: "Hybrid",
    experience: "5 - 8 years",
    experienceLevel: "Senior",
    salaryMin: 28,
    salaryMax: 45,
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD"],
    description:
      "Own the platform that forty engineers deploy to every day. We have outgrown our hand-rolled scripts and need someone to bring real infrastructure-as-code discipline to our AWS setup.",
    requirements: [
      "5+ years in DevOps, SRE or platform engineering",
      "Production experience running Kubernetes",
      "Strong Terraform and AWS knowledge",
      "Scripting in Python, Go or Bash",
    ],
    benefits: ["Stock options", "Health insurance", "Conference budget"],
    department: "Engineering",
    openings: 1,
    postedDate: "2026-08-21",
    status: "Open",
  },
  {
    id: "job-006",
    title: "Frontend Developer Intern",
    company: "Kite & Co.",
    companyInitials: "KC",
    location: "Remote, India",
    jobType: "Internship",
    workMode: "Remote",
    experience: "0 - 1 years",
    experienceLevel: "Entry",
    salaryMin: 3,
    salaryMax: 5,
    skills: ["HTML", "CSS", "JavaScript", "React"],
    description:
      "A six month paid internship for someone early in their journey. You will pair with senior engineers, ship small features to real users, and leave with a portfolio you are proud of.",
    requirements: [
      "Comfortable with HTML, CSS and JavaScript fundamentals",
      "Some exposure to React from coursework or personal projects",
      "Able to use Git and open a pull request",
      "Curious, and happy to ask questions",
    ],
    benefits: ["Paid internship", "Dedicated mentor", "Possible full-time offer"],
    department: "Engineering",
    openings: 4,
    postedDate: "2026-09-05",
    status: "Open",
  },
  {
    id: "job-007",
    title: "HR Business Partner",
    company: "Harbour Retail Group",
    companyInitials: "HR",
    location: "Gurugram, India",
    jobType: "Full-time",
    workMode: "On-site",
    experience: "5 - 9 years",
    experienceLevel: "Senior",
    salaryMin: 20,
    salaryMax: 30,
    skills: ["Employee Relations", "Performance Management", "Coaching"],
    description:
      "Partner with two business units totalling 600 people. You will coach managers, run the performance cycle, and be the person people trust when something difficult comes up.",
    requirements: [
      "5+ years in an HR generalist or HRBP role",
      "Strong grounding in Indian labour law",
      "Experience handling employee relations cases end to end",
      "Comfortable presenting to senior leadership",
    ],
    benefits: ["Family health cover", "Annual bonus", "Employee discount"],
    department: "Human Resources",
    openings: 1,
    postedDate: "2026-08-19",
    status: "Open",
  },
  {
    id: "job-008",
    title: "QA Automation Engineer",
    company: "Meridian Health",
    companyInitials: "MH",
    location: "Chennai, India",
    jobType: "Contract",
    workMode: "Remote",
    experience: "3 - 6 years",
    experienceLevel: "Mid",
    salaryMin: 12,
    salaryMax: 20,
    skills: ["Playwright", "TypeScript", "API Testing", "CI/CD"],
    description:
      "A twelve month contract to build our end-to-end test suite from scratch. Regression testing is manual today and takes three days - your job is to make that a twenty minute pipeline run.",
    requirements: [
      "3+ years in test automation",
      "Strong with Playwright, Cypress or similar",
      "Able to write maintainable TypeScript",
      "Experience introducing automation where none existed",
    ],
    benefits: ["Fully remote", "12 month contract", "Equipment provided"],
    department: "Engineering",
    openings: 1,
    postedDate: "2026-08-14",
    status: "Open",
  },
];

/** Every distinct company in the seed data. */
export const COMPANIES = Array.from(new Set(SEED_JOBS.map((job) => job.company))).sort();
